
function m_gui
h_figure=figure('Units','characters',...
'Position',[2 3 120 35],...
'Color',get(0,'DefaultUicontrolBackgroundColor'));
h_axes=axes('Units','characters',...
'Position',[10 6 70 25],...
'Parent',h_figure);
h_listbox_label=uicontrol(h_figure,...
'Style','text',...
'Units','characters',...
'Position',[88 29 24 2],...
'String','Selsect a triangle function');
h_listbox=uicontrol(h_figure,...
'Style','listbox',...
'Units','characters',...
'Position',[88 18.5 24 10],...
'BackgroundColor','white',...
'Max',10,'Min',1,...
'CallBack',@listbox_callback);
h_popup_label=uicontrol(h_figure,...
'Style','text',...
'Units','characters',...
'Position',[88 13 24 2],...
'String','Plot Type');
h_popup=uicontrol(h_figure,...
'Style','popupmenu',...
'Units','characters',...
'Position',[88 12 24 2],...
'BackgroundColor','white',...
'String',{'Plot','Stairs','Stem'});
h_hold_toggle=uicontrol(h_figure,...
'Style','toggle',...
'Units','characters',...
'Position',[88 8 24 2],...
'String','Hold State',...
'CallBack',{@hold_toggle_callback,h_axes});
h_linewidth_label=uicontrol(h_figure,...
'Style','text',...
'Units','characters',...
'Position',[6 2 20 2],...
'String','set line width');
h_line_width=uicontrol(h_figure,...
'Style','slider',...
'Units','characters',...
'Position',[25 3 50 1],...
'Max',16,'Min',1,'value',1,...
'CallBack',{@line_width_callback,h_axes});
h_plot_button=uicontrol(h_figure,...
'Style','pushbutton',...
'Units','characters',...
'Position',[88 3.5 24 2],...
'String','Creat Plot',...
'CallBack',{@plot_button_callback,h_listbox,...
h_popup,h_axes,h_line_width});
listbox_callback(h_listbox,[]);
hold_toggle_callback(h_hold_toggle,[],h_axes);
function listbox_callback(obj,eventdata)
vars={'cos(x)','cos(x/2)/2','sin(x)','sin(x/2)/2'};
set(obj,'String',vars);
function hold_toggle_callback(obj,eventdata,h_axes)
button_state=get(obj,'value');
if button_state==get(obj,'Max')
set(h_axes,'NextPlot','add');
set(obj,'String','Hold on');
elseif button_state==get(obj,'Min')
set(h_axes,'NextPlot','replace');
set(obj,'String','Hold off');
end
function plot_button_callback(obj,eventdata,...
h_listbox,h_popup,h_axes,h_line_width)
vars=get(h_listbox,'String');
var_index=get(h_listbox,'Value');
if length(var_index)~=1
errordlg('Must select one function','Error','modal');
return;
end
x=0:0.5:pi*3;
y=eval(vars{var_index});
axes(h_axes);
selected_cmd=get(h_popup,'Value');
switch selected_cmd
case 1
hp=plot(x,y);
case 2
hp=stairs(x,y);
case 3
hp=stem(x,y);
end
set(hp,'linewidth',get(h_line_width,'value'));
function line_width_callback(obj,eventdata,h_axes)
h=findobj(h_axes,'type','line');
set(h,'linewidth',get(obj,'value'));